name: Maven Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true
      branch:
        description: "The branch to release from"
        required: true
        default: 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: maven

      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }}

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          release-branch-name: "main"
          git-release-bot-name: "Release Bot"
          git-release-bot-email: "release-bot@idhub.io"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${ {secrets.SSH_PASSPHRASE }}

          # Release
          maven-servers: ${{ secrets.MAVEN_SERVERS }}
          maven-release-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"
