name: Build and Update Snapshot Version

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Validate unique development version
        id: validate-unique-version
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" != "main" ]; then
            echo "Releases can only be created from the main branch"
            exit 1
          fi
          if git ls-remote --exit-code --heads origin '*-development'; then
            echo "A development branch already exists"
            exit 1
          fi

      - name: Extract release version
        id: extract-release-version
        run: |
          release_version=${GITHUB_REF#refs/tags/}
          echo "Release version: $release_version"
          echo "::set-output name=release_version::$release_version"

      - name: Update POM to release version
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Calculate next snapshot version
        id: calculate-version
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          
          # Increment patch version
          IFS='.' read -r -a version_parts <<< "$release_version"
          version_parts[2]=$((version_parts[2] + 1))
          next_snapshot_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}-SNAPSHOT"
          echo "Next snapshot version: $next_snapshot_version"
          
          # Set output variable
          echo "::set-output name=next_snapshot_version::$next_snapshot_version"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git to use SSH
        run: |
          git remote set-url origin git@github.com:ueno-tecnologia-org/spring-boot-starter-data-mongodb-secured.git

      - name: Checkout main branch
        run: |
          git fetch origin main:main
          git checkout main

      - name: Config Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Restore POM to release version on main
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit
          cat pom.xml
          git add pom.xml
          git commit -m "Restore POM to release version $release_version"
          git push origin main

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create branch for next snapshot version
        run: |
          echo "Checking out new branch: ${{ steps.calculate-version.outputs.next_snapshot_version }}-development"
          git checkout -b ${{ steps.calculate-version.outputs.next_snapshot_version }}-development
          
          echo "Setting new Maven version: ${{ steps.calculate-version.outputs.next_snapshot_version }}"
          mvn versions:set -DnewVersion=${{ steps.calculate-version.outputs.next_snapshot_version }}
          mvn versions:commit
          
          echo "Adding changes to git"
          git add pom.xml
          
          echo "Committing changes"
          git commit -m "Prepare for the next development iteration"
          
          echo "Verifying commit"
          git show --pretty="" --name-only $(git log --format="%H" -n 1)
          
          echo "Pushing changes to new branch"
          git push origin ${{ steps.calculate-version.outputs.next_snapshot_version }}-development
          
        
