name: Build and Update Snapshot Version

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Calculate next snapshot version
        id: calculate-version
        run: |
          # Extract current version from pom.xml
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          
          # Remove "-SNAPSHOT" if present
          release_version=${current_version/-SNAPSHOT/}
          
          # Increment patch version
          IFS='.' read -r -a version_parts <<< "$release_version"
          version_parts[2]=$((version_parts[2] + 1))
          next_snapshot_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}-SNAPSHOT"
          echo "Next snapshot version: $next_snapshot_version"
          
          # Set output variable
          echo "::set-output name=next_snapshot_version::$next_snapshot_version"

      - name: Update POM to next snapshot version
        run: |
          next_snapshot_version=${{ steps.calculate-version.outputs.next_snapshot_version }}
          mvn versions:set -DnewVersion=$next_snapshot_version
          mvn versions:commit

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Commit and push changes to dev
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b dev
          git add pom.xml
          git commit -m "Update to version ${{ steps.calculate-version.outputs.next_snapshot_version }}"
          git push origin dev

      - name: Restore POM to release version on main
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          release_version=${current_version/-SNAPSHOT/}
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit
          git add pom.xml
          git commit -m "Restore POM to release version $release_version"
          git push origin main
