name: Build and Update snapshot version

on:
  push:
    branches:
      - '*-development'

jobs:
  delete-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Leer nombre del paquete desde pom.xml
        id: get-package-name
        run: |
          PACKAGE_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive)
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive)
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up environment
        run: |
          PACKAGE_VERSION=${{ env.VERSION }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "OWNER=${OWNER}" >> $GITHUB_ENV
          echo "REPO=${REPO}" >> $GITHUB_ENV

      - name: Delete package version
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        run: |
          curl -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${OWNER}/packages/container/${PACKAGE_NAME}/versions/${PACKAGE_VERSION}TOKEN: ${{ secrets.TOKEN }}

          - name: Publish to GitHub Packages
            run: mvn deploy
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
