name: Build and Update Snapshot Version

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Extract release version
        id: extract-release-version
        run: |
          release_version=${GITHUB_REF#refs/tags/}
          echo "Release version: $release_version"
          echo "::set-output name=release_version::$release_version"

      - name: Update POM to release version
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean install

      - name: Calculate next snapshot version
        id: calculate-version
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          
          # Increment patch version
          IFS='.' read -r -a version_parts <<< "$release_version"
          version_parts[2]=$((version_parts[2] + 1))
          next_snapshot_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}-SNAPSHOT"
          echo "Next snapshot version: $next_snapshot_version"
          
          # Set output variable
          echo "::set-output name=next_snapshot_version::$next_snapshot_version"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git to use SSH
        run: |
          git remote set-url origin git@github.com:ueno-tecnologia-org/spring-boot-starter-data-mongodb-secured.git

      - name: Checkout main branch
        run: |
          git fetch origin main:main
          git checkout main

      - name: Config Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Restore POM to release version on main
        run: |
          release_version=${{ steps.extract-release-version.outputs.release_version }}
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit
          git add pom.xml
          git commit -m "Restore POM to release version $release_version"
          git push origin main

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create branch for next snapshot version
        run: |
          git checkout -b snapshot-${{ steps.calculate-version.outputs.next_snapshot_version }}-bump
          mvn versions:set -DnewVersion=${{ steps.calculate-version.outputs.next_snapshot_version }}
          mvn versions:commit
          git add pom.xml
          git commit -m "Restore POM to release version $release_version"
          git push origin HEAD

      - name: Raise PR for next snapshot version
        id: raise-pr-for-next-snapshot-version
        uses: peter-evans/create-pull-request@v3
        with:
          branch: snapshot-${{ steps.calculate-version.outputs.next_snapshot_version }}-bump
          base: develop
          title: "Prepare for next development iteration"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: |
            Bumps the version to ${{ steps.calculate-version.outputs.next_snapshot_version }} for the next development iteration.
          token: ${{ secrets.TOKEN }}
          delete-branch: true


