name: Maven Release

on:
  release:
   types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Calculate versions
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.event.inputs.version }}"
          echo "RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV
          echo "NEXT_VERSION=$(echo $RELEASE_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')" >> $GITHUB_ENV

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          release-branch-name: "main"
          # Release
          maven-development-version-number: ${{ env.NEXT_VERSION }}-SNAPSHOT
          maven-release-version-number: ${{ env.RELEASE_VERSION }}
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.USERNAME}}
          maven-repo-server-password: ${{ secrets.TOKEN }}
          maven-release-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"
