name: Test

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set the RELEASE_BRANCH_NAME
        run: echo "RELEASE_BRANCH_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
